[package]
name = "test-shadow-core"
version = "0.1.0"
edition = "2018"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
const-zero = { path = ".." }
core = { package = "not-core", path = "../not-core" }
